<a href="https://colab.research.google.com/github/miso-20/ESSA/blob/main/ESAA_YB_WEEK_09_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이썬 머신러닝 완벽가이드 ch4. p. 267~295

## 09. 분류 실습-캐글 산탄데르 고객 만족 예측

모델의 성능 평가는 ROC-AUC(ROC 곡선 영역)로 평가

대부분이 만족이고 불만족인 데이터는 일부일 것이기 때문에 정확도 수치보다는 ROC—AUC가 더 적합

### 1) 데이터 전처리

In [20]:
### 추가 ###
!pip install xgboost==1.7.6
!pip install lightgbm==4.1.0

Requirement already satisfied: xgboost==1.7.6 in /usr/local/lib/python3.12/dist-packages (1.7.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost==1.7.6) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost==1.7.6) (1.16.3)
Requirement already satisfied: lightgbm==4.1.0 in /usr/local/lib/python3.12/dist-packages (4.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from lightgbm==4.1.0) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm==4.1.0) (1.16.3)

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pit
import matplotlib
import warnings
warnings.filterwarnings('ignore')
cust_df = pd.read_csv("/content/drive/MyDrive/YB_data/train_santander.csv", encoding='latin-1')
print('dataset shape:',cust_df.shape)
cust_df.head(3)

dataset shape: (76020, 371)

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.17,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.03,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.77,0

In [22]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB

In [23]:
print(cust_df['TARGET'].value_counts())
unsatisfied_cnt = cust_df[cust_df['TARGET'] == 1].TARGET.count()
total_cnt = cust_df.TARGET.count()
print('unsatisfied 배율은 {0:.2f}'.format((unsatisfied_cnt / total_cnt)))

TARGET
0    73012
1     3008
Name: count, dtype: int64
unsatisfied 배율은 0.04

In [24]:
cust_df.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07,1.000000

In [25]:
cust_df['var3'].replace(-999999, 2, inplace=True)
cust_df.drop('ID', axis=1, inplace=True)

# 피처 세트와 레이블 세트 분리. 레이블 칼럼은 DataFrame의 맨 마지막에 위치해 칼럼 위치 -1 로 분리
X_features = cust_df.iloc[:, :-1]
y_labels = cust_df.iloc[:, -1]
print('피처 데이터 shape:{0}'.format(X_features.shape))

피처 데이터 shape:(76020, 369)

학습과 성능 평가를 위해서 원본 데이터 세트에서 학습 데이터 세트와 테스트 데이터 세트를 분리

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_features, y_labels,
                                                    test_size=0.2, random_state=0)
train_cnt = y_train.count()
test_cnt = y_test. count()
print('학습 세트 Shape:{0}, 테스트 세트 Shape:{1}' .format(X_train.shape, X_test.shape))

print('학습 세트 레이블 값 분포 비율' )
print(y_train.value_counts()/train_cnt)
print('\n 테스트 세트 레이블 값 분포 비율')
print(y_test.value_counts()/test_cnt)

학습 세트 Shape:(60816, 369), 테스트 세트 Shape:(15204, 369)
학습 세트 레이블 값 분포 비율
TARGET
0    0.960964
1    0.039036
Name: count, dtype: float64

 테스트 세트 레이블 값 분포 비율
TARGET
0    0.9583
1    0.0417
Name: count, dtype: float64

In [27]:
# X_train, y_train을 다시 학습과 검증 데이터 세트로 분리.
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=0)

### 2) XGBoost 모델 학습과 하이퍼 파라미터 튜닝

In [28]:
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

# n_estimators는 500으로, random state는 예제 수행 시마다 동일 예측 결과를 위해 설정.
xgb_clf = XGBClassifier(n_estimators=500, learning_rate=0.05, random_state=156)

# 성능 평가 지표를 auc로, 조기 중단 파라미터는 100으로 설정하고 학습 수행.
xgb_clf.fit(X_tr, y_tr, early_stopping_rounds=100, eval_metric="auc", eval_set=[(X_tr, y_tr),
 (X_val, y_val)])

xgb_roc_score = roc_auc_score(y_test, xgb_clf.predict_proba(X_test)[:, 1 ])
print('ROC AUC: {0:.4f}'.format(xgb_roc_score))

[0]	validation_0-auc:0.82179	validation_1-auc:0.80068
[1]	validation_0-auc:0.82347	validation_1-auc:0.80523
[2]	validation_0-auc:0.83178	validation_1-auc:0.81097
[3]	validation_0-auc:0.83401	validation_1-auc:0.81091
[4]	validation_0-auc:0.83443	validation_1-auc:0.81040
[5]	validation_0-auc:0.83570	validation_1-auc:0.81089
[6]	validation_0-auc:0.83597	validation_1-auc:0.81057
[7]	validation_0-auc:0.83643	validation_1-auc:0.81082
[8]	validation_0-auc:0.83682	validation_1-auc:0.81147
[9]	validation_0-auc:0.83769	validation_1-auc:0.81188
[10]	validation_0-auc:0.83770	validation_1-auc:0.81163
[11]	validation_0-auc:0.83911	validation_1-auc:0.81355
[12]	validation_0-auc:0.83976	validation_1-auc:0.81336
[13]	validation_0-auc:0.84038	validation_1-auc:0.81365
[14]	validation_0-auc:0.84176	validation_1-auc:0.81419
[15]	validation_0-auc:0.84306	validation_1-auc:0.81586
[16]	validation_0-auc:0.84343	validation_1-auc:0.81610
[17]	validation_0-auc:0.84373	validation_1-auc:0.81584
[18]	validation_0-auc:0.84542	validation_1-auc:0.81581
[19]	validation_0-auc:0.84580	validation_1-auc:0.81622
[20]	validation_0-auc:0.84656	validation_1-auc:0.81641
[21]	validation_0-auc:0.84732	validation_1-auc:0.81740
[22]	validation_0-auc:0.84769	validation_1-auc:0.81748
[23]	validation_0-auc:0.84833	validation_1-auc:0.81744
[24]	validation_0-auc:0.84836	validation_1-auc:0.81704
[25]	validation_0-auc:0.84892	validation_1-auc:0.81650
[26]	validation_0-auc:0.85114	validation_1-auc:0.81730
[27]	validation_0-auc:0.85293	validation_1-auc:0.81843
[28]	validation_0-auc:0.85335	validation_1-auc:0.81883
[29]	validation_0-auc:0.85441	validation_1-auc:0.82072
[30]	validation_0-auc:0.85604	validation_1-auc:0.82169
[31]	validation_0-auc:0.85755	validation_1-auc:0.82256
[32]	validation_0-auc:0.85830	validation_1-auc:0.82267
[33]	validation_0-auc:0.85895	validation_1-auc:0.82321
[34]	validation_0-auc:0.85964	validation_1-auc:0.82332
[35]	validation_0-auc:0.85988	validation_1-auc:0.82408
[36]	validation_0-auc:0.86037	validation_1-auc:0.82452
[37]	validation_0-auc:0.86075	validation_1-auc:0.82466
[38]	validation_0-auc:0.86171	validation_1-auc:0.82554
[39]	validation_0-auc:0.86241	validation_1-auc:0.82582
[40]	validation_0-auc:0.86277	validation_1-auc:0.82590
[41]	validation_0-auc:0.86347	validation_1-auc:0.82628
[42]	validation_0-auc:0.86401	validation_1-auc:0.82668
[43]	validation_0-auc:0.86473	validation_1-auc:0.82686
[44]	validation_0-auc:0.86523	validation_1-auc:0.82692
[45]	validation_0-auc:0.86622	validation_1-auc:0.82774
[46]	validation_0-auc:0.86721	validation_1-auc:0.82834
[47]	validation_0-auc:0.86776	validation_1-auc:0.82831
[48]	validation_0-auc:0.86837	validation_1-auc:0.82909
[49]	validation_0-auc:0.86916	validation_1-auc:0.82997
[50]	validation_0-auc:0.86939	validation_1-auc:0.82984
[51]	validation_0-auc:0.87005	validation_1-auc:0.83006
[52]	validation_0-auc:0.87057	validation_1-auc:0.83039
[53]	validation_0-auc:0.87088	validation_1-auc:0.83066
[54]	validation_0-auc:0.87145	validation_1-auc:0.83105
[55]	validation_0-auc:0.87222	validation_1-auc:0.83139
[56]	validation_0-auc:0.87285	validation_1-auc:0.83167
[57]	validation_0-auc:0.87329	validation_1-auc:0.83175
[58]	validation_0-auc:0.87375	validation_1-auc:0.83170
[59]	validation_0-auc:0.87419	validation_1-auc:0.83196
[60]	validation_0-auc:0.87465	validation_1-auc:0.83191
[61]	validation_0-auc:0.87537	validation_1-auc:0.83186
[62]	validation_0-auc:0.87612	validation_1-auc:0.83187
[63]	validation_0-auc:0.87663	validation_1-auc:0.83192
[64]	validation_0-auc:0.87751	validation_1-auc:0.83194
[65]	validation_0-auc:0.87825	validation_1-auc:0.83218
[66]	validation_0-auc:0.87880	validation_1-auc:0.83248
[67]	validation_0-auc:0.87937	validation_1-auc:0.83241
[68]	validation_0-auc:0.87980	validation_1-auc:0.83239
[69]	validation_0-auc:0.88044	validation_1-auc:0.83249
[70]	validation_0-auc:0.88105	validation_1-auc:0.83229
[71]	validation_0-auc:0.88163	validation_1-auc:0.83261
[72]	validation_0-auc:0.88212	validation_1-auc:0.83251
[73]	validation_0-auc:0.88263	validation_1-auc:0.83257
[74]	validation_0-auc:0.88311	validation_1-auc:0.83258
[75]	validation_0-auc:0.88357	validation_1-auc:0.83255
[76]	validation_0-auc:0.88411	validation_1-auc:0.83264
[77]	validation_0-auc:0.88458	validation_1-auc:0.83241
[78]	validation_0-auc:0.88490	validation_1-auc:0.83232
[79]	validation_0-auc:0.88539	validation_1-auc:0.83249
[80]	validation_0-auc:0.88609	validation_1-auc:0.83251
[81]	validation_0-auc:0.88656	validation_1-auc:0.83261
[82]	validation_0-auc:0.88688	validation_1-auc:0.83265
[83]	validation_0-auc:0.88735	validation_1-auc:0.83258
[84]	validation_0-auc:0.88770	validation_1-auc:0.83270
[85]	validation_0-auc:0.88825	validation_1-auc:0.83251
[86]	validation_0-auc:0.88890	validation_1-auc:0.83240
[87]	validation_0-auc:0.88928	validation_1-auc:0.83229
[88]	validation_0-auc:0.88958	validation_1-auc:0.83225
[89]	validation_0-auc:0.88997	validation_1-auc:0.83205
[90]	validation_0-auc:0.89030	validation_1-auc:0.83210
[91]	validation_0-auc:0.89067	validation_1-auc:0.83223
[92]	validation_0-auc:0.89098	validation_1-auc:0.83212
[93]	validation_0-auc:0.89125	validation_1-auc:0.83198
[94]	validation_0-auc:0.89166	validation_1-auc:0.83198
[95]	validation_0-auc:0.89191	validation_1-auc:0.83196
[96]	validation_0-auc:0.89219	validation_1-auc:0.83181
[97]	validation_0-auc:0.89253	validation_1-auc:0.83184
[98]	validation_0-auc:0.89286	validation_1-auc:0.83176
[99]	validation_0-auc:0.89310	validation_1-auc:0.83184
[100]	validation_0-auc:0.89337	validation_1-auc:0.83176
[101]	validation_0-auc:0.89375	validation_1-auc:0.83168
[102]	validation_0-auc:0.89392	validation_1-auc:0.83175
[103]	validation_0-auc:0.89418	validation_1-auc:0.83162
[104]	validation_0-auc:0.89446	validation_1-auc:0.83162
[105]	validation_0-auc:0.89483	validation_1-auc:0.83173
[106]	validation_0-auc:0.89530	validation_1-auc:0.83182
[107]	validation_0-auc:0.89551	validation_1-auc:0.83179
[108]	validation_0-auc:0.89576	validation_1-auc:0.83190
[109]	validation_0-auc:0.89621	validation_1-auc:0.83190
[110]	validation_0-auc:0.89631	validation_1-auc:0.83198
[111]	validation_0-auc:0.89645	validation_1-auc:0.83200
[112]	validation_0-auc:0.89657	validation_1-auc:0.83214
[113]	validation_0-auc:0.89690	validation_1-auc:0.83221
[114]	validation_0-auc:0.89720	validation_1-auc:0.83223
[115]	validation_0-auc:0.89735	validation_1-auc:0.83218
[116]	validation_0-auc:0.89769	validation_1-auc:0.83236
[117]	validation_0-auc:0.89799	validation_1-auc:0.83245
[118]	validation_0-auc:0.89851	validation_1-auc:0.83253
[119]	validation_0-auc:0.89868	validation_1-auc:0.83256
[120]	validation_0-auc:0.89875	validation_1-auc:0.83269
[121]	validation_0-auc:0.89930	validation_1-auc:0.83258
[122]	validation_0-auc:0.89939	validation_1-auc:0.83269
[123]	validation_0-auc:0.89989	validation_1-auc:0.83274
[124]	validation_0-auc:0.90029	validation_1-auc:0.83308
[125]	validation_0-auc:0.90067	validation_1-auc:0.83324
[126]	validation_0-auc:0.90115	validation_1-auc:0.83325
[127]	validation_0-auc:0.90124	validation_1-auc:0.83324
[128]	validation_0-auc:0.90147	validation_1-auc:0.83324
[129]	validation_0-auc:0.90185	validation_1-auc:0.83337
[130]	validation_0-auc:0.90211	validation_1-auc:0.83336
[131]	validation_0-auc:0.90236	validation_1-auc:0.83341
[132]	validation_0-auc:0.90266	validation_1-auc:0.83351
[133]	validation_0-auc:0.90290	validation_1-auc:0.83346
[134]	validation_0-auc:0.90299	validation_1-auc:0.83362
[135]	validation_0-auc:0.90310	validation_1-auc:0.83363
[136]	validation_0-auc:0.90327	validation_1-auc:0.83355
[137]	validation_0-auc:0.90330	validation_1-auc:0.83354
[138]	validation_0-auc:0.90337	validation_1-auc:0.83357
[139]	validation_0-auc:0.90353	validation_1-auc:0.83348
[140]	validation_0-auc:0.90363	validation_1-auc:0.83353
[141]	validation_0-auc:0.90371	validation_1-auc:0.83346
[142]	validation_0-auc:0.90395	validation_1-auc:0.83341
[143]	validation_0-auc:0.90397	validation_1-auc:0.83341
[144]	validation_0-auc:0.90422	validation_1-auc:0.83340
[145]	validation_0-auc:0.90446	validation_1-auc:0.83335
[146]	validation_0-auc:0.90467	validation_1-auc:0.83354
[147]	validation_0-auc:0.90482	validation_1-auc:0.83355
[148]	validation_0-auc:0.90484	validation_1-auc:0.83356
[149]	validation_0-auc:0.90500	validation_1-auc:0.83353
[150]	validation_0-auc:0.90513	validation_1-auc:0.83352
[151]	validation_0-auc:0.90531	validation_1-auc:0.83349
[152]	validation_0-auc:0.90548	validation_1-auc:0.83349
[153]	validation_0-auc:0.90551	validation_1-auc:0.83351
[154]	validation_0-auc:0.90563	validation_1-auc:0.83348
[155]	validation_0-auc:0.90572	validation_1-auc:0.83343
[156]	validation_0-auc:0.90579	validation_1-auc:0.83344
[157]	validation_0-auc:0.90591	validation_1-auc:0.83345
[158]	validation_0-auc:0.90621	validation_1-auc:0.83355
[159]	validation_0-auc:0.90630	validation_1-auc:0.83359
[160]	validation_0-auc:0.90643	validation_1-auc:0.83356
[161]	validation_0-auc:0.90657	validation_1-auc:0.83352
[162]	validation_0-auc:0.90672	validation_1-auc:0.83346
[163]	validation_0-auc:0.90694	validation_1-auc:0.83347
[164]	validation_0-auc:0.90714	validation_1-auc:0.83343
[165]	validation_0-auc:0.90720	validation_1-auc:0.83343
[166]	validation_0-auc:0.90727	validation_1-auc:0.83337
[167]	validation_0-auc:0.90730	validation_1-auc:0.83335
[168]	validation_0-auc:0.90737	validation_1-auc:0.83333
[169]	validation_0-auc:0.90741	validation_1-auc:0.83337
[170]	validation_0-auc:0.90772	validation_1-auc:0.83335
[171]	validation_0-auc:0.90778	validation_1-auc:0.83332
[172]	validation_0-auc:0.90781	validation_1-auc:0.83337
[173]	validation_0-auc:0.90786	validation_1-auc:0.83337
[174]	validation_0-auc:0.90797	validation_1-auc:0.83326
[175]	validation_0-auc:0.90802	validation_1-auc:0.83334
[176]	validation_0-auc:0.90818	validation_1-auc:0.83335
[177]	validation_0-auc:0.90832	validation_1-auc:0.83330
[178]	validation_0-auc:0.90836	validation_1-auc:0.83332
[179]	validation_0-auc:0.90850	validation_1-auc:0.83339
[180]	validation_0-auc:0.90856	validation_1-auc:0.83340
[181]	validation_0-auc:0.90864	validation_1-auc:0.83338
[182]	validation_0-auc:0.90890	validation_1-auc:0.83335
[183]	validation_0-auc:0.90899	validation_1-auc:0.83327
[184]	validation_0-auc:0.90902	validation_1-auc:0.83330
[185]	validation_0-auc:0.90913	validation_1-auc:0.83330
[186]	validation_0-auc:0.90934	validation_1-auc:0.83352
[187]	validation_0-auc:0.90939	validation_1-auc:0.83356
[188]	validation_0-auc:0.90947	validation_1-auc:0.83346
[189]	validation_0-auc:0.90955	validation_1-auc:0.83347
[190]	validation_0-auc:0.90978	validation_1-auc:0.83341
[191]	validation_0-auc:0.90982	validation_1-auc:0.83340
[192]	validation_0-auc:0.90987	validation_1-auc:0.83342
[193]	validation_0-auc:0.90999	validation_1-auc:0.83339
[194]	validation_0-auc:0.91010	validation_1-auc:0.83338
[195]	validation_0-auc:0.91015	validation_1-auc:0.83329
[196]	validation_0-auc:0.91018	validation_1-auc:0.83331
[197]	validation_0-auc:0.91021	validation_1-auc:0.83333
[198]	validation_0-auc:0.91029	validation_1-auc:0.83338
[199]	validation_0-auc:0.91050	validation_1-auc:0.83338
[200]	validation_0-auc:0.91056	validation_1-auc:0.83338
[201]	validation_0-auc:0.91061	validation_1-auc:0.83334
[202]	validation_0-auc:0.91065	validation_1-auc:0.83333
[203]	validation_0-auc:0.91068	validation_1-auc:0.83334
[204]	validation_0-auc:0.91079	validation_1-auc:0.83336
[205]	validation_0-auc:0.91091	validation_1-auc:0.83323
[206]	validation_0-auc:0.91098	validation_1-auc:0.83316
[207]	validation_0-auc:0.91119	validation_1-auc:0.83319
[208]	validation_0-auc:0.91131	validation_1-auc:0.83320
[209]	validation_0-auc:0.91160	validation_1-auc:0.83331
[210]	validation_0-auc:0.91165	validation_1-auc:0.83329
[211]	validation_0-auc:0.91182	validation_1-auc:0.83325
[212]	validation_0-auc:0.91189	validation_1-auc:0.83330
[213]	validation_0-auc:0.91198	validation_1-auc:0.83329
[214]	validation_0-auc:0.91219	validation_1-auc:0.83321
[215]	validation_0-auc:0.91225	validation_1-auc:0.83326
[216]	validation_0-auc:0.91228	validation_1-auc:0.83329
[217]	validation_0-auc:0.91234	validation_1-auc:0.83326
[218]	validation_0-auc:0.91258	validation_1-auc:0.83311
[219]	validation_0-auc:0.91269	validation_1-auc:0.83311
[220]	validation_0-auc:0.91279	validation_1-auc:0.83305
[221]	validation_0-auc:0.91301	validation_1-auc:0.83310
[222]	validation_0-auc:0.91311	validation_1-auc:0.83307
[223]	validation_0-auc:0.91318	validation_1-auc:0.83310
[224]	validation_0-auc:0.91333	validation_1-auc:0.83308
[225]	validation_0-auc:0.91340	validation_1-auc:0.83309
[226]	validation_0-auc:0.91340	validation_1-auc:0.83307
[227]	validation_0-auc:0.91357	validation_1-auc:0.83310
[228]	validation_0-auc:0.91360	validation_1-auc:0.83310
[229]	validation_0-auc:0.91367	validation_1-auc:0.83312
[230]	validation_0-auc:0.91378	validation_1-auc:0.83313
[231]	validation_0-auc:0.91382	validation_1-auc:0.83313
[232]	validation_0-auc:0.91383	validation_1-auc:0.83314
[233]	validation_0-auc:0.91405	validation_1-auc:0.83312
[234]	validation_0-auc:0.91414	validation_1-auc:0.83307
[235]	validation_0-auc:0.91415	validation_1-auc:0.83305
ROC AUC: 0.8429

In [29]:
from hyperopt import hp

# max_depth는 5에서 15까지 1 간격으로, min_child_weight는 1에서 6까지 1 간격으로
# colsample_bytree는 0.5에서 0.95 사이, learning_rate는 0.01 에서 0.2 사이 정규 분포된 값으로 검색.
xgb_search_space = {'max_depth':hp.quniform('max_depth', 5, 15, 1),
                    'min_child_weight': hp.quniform('min_child_weight', 1, 6, 1),
                    'colsample_bytree': hp.uniform('colsample.bytree', 0.5, 0.95),
                    'learning_rate': hp.uniform('learning_rate', 0.01, 0.2) }

교차 검증 시 XGBoost의 조기 중단과 검증 데이터 성능 평가를 위해서 KFold 클래스를 이용하여 직접 학습과 검증
데이터 세트를 추출하고 이를 교차 검증 횟수만큼 학습과 성능 평가를 수행

In [30]:
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score

# fmin()에서 호출 시 search_space 값으로 XGBClassifier 교차 검증 학습 후 -1* roc_auc 평균 값을 반환.
def objective_func(search_space):
  xgb_clf = XGBClassifier(n_estimators=100, max_depth=int(search_space['max_depth']),
                          min_child_weight=int(search_space['min_child_weight']),
                          colsample_bytree=search_space['colsample_bytree'],
                          learning_rate=search_space['learning_rate'])
  # 3개 k-fold 방식으로 평가된 roc_auc 지표를 담는 list
  roc_auc_list = [ ]

  # 3개 k-fold 방식 적용
  kf = KFold(n_splits=3)
  # X_train을 다시 학습과 검증용 데이터로 분리
  for tr_index, val_index in kf.split(X_train):
    # kf .split(X_train)으로 추출된 학습과 검증 index 값으로 학습과 검증 데이터 세트 분리
    X_tr, y_tr = X_train.iloc[tr_index], y_train.iloc[tr_index]
    X_val, y_val = X_train.iloc[val_index], y_train.iloc[val_index]

    # early stopping은 30회로 설정하고 추출된 학습과 검증 데이터로 XGBClassifier 학습 수행.
    xgb_clf.fit(X_tr, y_tr, early_stopping_rounds=30, eval_metric="auc",
      eval_set=[(X_tr, y_tr), (X_val, y_val)])

    # 1 로 예측한 확률값 추출 후 roc auc 계산하고 평균 roc auc 계산을 위해 list에 결괏값 담음.
    score = roc_auc_score(y_val, xgb_clf.predict_proba(X_val)[:, 1 ])
    roc_auc_list.append(score)

  # 3개 k-fold로 계산된 roc.auc 값의 평균값을 반환하되,
  # HyperOpt는 목적함수의 최솟값을 위한 입력값을 찾으므로 -1을 곱한 뒤 반환.
  return -1*np.mean(roc_auc_list)

In [ ]:
from hyperopt import fmin, tpe, Trials

trials = Trials()

# fmin() 함수를 호출. max.evals 지정된 횟수만큼 반복 후 목적함수의 최솟값을 가지는 최적 입력값 추출.
best = fmin(fn=objective_func,
            space=xgb_search_space,
            algo=tpe.suggest,
            max_evals=50, # 최대 반복 횟수를 지정합니다.
            trials=trials, rstate=np.random.default_rng(seed=30))

print('best:', best)

[0]	validation_0-auc:0.82172	validation_1-auc:0.79884
[1]	validation_0-auc:0.81786	validation_1-auc:0.79065
[2]	validation_0-auc:0.83199	validation_1-auc:0.80639
[3]	validation_0-auc:0.83262	validation_1-auc:0.80859
[4]	validation_0-auc:0.83830	validation_1-auc:0.81264
[5]	validation_0-auc:0.84130	validation_1-auc:0.81562
[6]	validation_0-auc:0.84344	validation_1-auc:0.81736
[7]	validation_0-auc:0.84457	validation_1-auc:0.81739
[8]	validation_0-auc:0.84520	validation_1-auc:0.81817
[9]	validation_0-auc:0.84586	validation_1-auc:0.81742
[10]	validation_0-auc:0.84650	validation_1-auc:0.81681
[11]	validation_0-auc:0.84763	validation_1-auc:0.81716
[12]	validation_0-auc:0.84835	validation_1-auc:0.81818
[13]	validation_0-auc:0.84903	validation_1-auc:0.81854
[14]	validation_0-auc:0.85096	validation_1-auc:0.82041
[15]	validation_0-auc:0.85222	validation_1-auc:0.82126
[16]	validation_0-auc:0.85296	validation_1-auc:0.82089
[17]	validation_0-auc:0.85455	validation_1-auc:0.82230
[18]	validation_0-auc:0.85622	validation_1-auc:0.82288
[19]	validation_0-auc:0.85684	validation_1-auc:0.82305
[20]	validation_0-auc:0.85848	validation_1-auc:0.82435
[21]	validation_0-auc:0.85946	validation_1-auc:0.82582
[22]	validation_0-auc:0.86063	validation_1-auc:0.82670
[23]	validation_0-auc:0.86166	validation_1-auc:0.82764
[24]	validation_0-auc:0.86304	validation_1-auc:0.82784
[25]	validation_0-auc:0.86442	validation_1-auc:0.82796
[26]	validation_0-auc:0.86530	validation_1-auc:0.82801
[27]	validation_0-auc:0.86649	validation_1-auc:0.82878
[28]	validation_0-auc:0.86751	validation_1-auc:0.82864
[29]	validation_0-auc:0.86817	validation_1-auc:0.82858
[30]	validation_0-auc:0.86899	validation_1-auc:0.82876
[31]	validation_0-auc:0.86936	validation_1-auc:0.82903
[32]	validation_0-auc:0.87032	validation_1-auc:0.82980
[33]	validation_0-auc:0.87055	validation_1-auc:0.83064
[34]	validation_0-auc:0.87107	validation_1-auc:0.83086
[35]	validation_0-auc:0.87213	validation_1-auc:0.83173
[36]	validation_0-auc:0.87281	validation_1-auc:0.83149
[37]	validation_0-auc:0.87332	validation_1-auc:0.83176
[38]	validation_0-auc:0.87493	validation_1-auc:0.83215
[39]	validation_0-auc:0.87582	validation_1-auc:0.83241
[40]	validation_0-auc:0.87712	validation_1-auc:0.83213
[41]	validation_0-auc:0.87773	validation_1-auc:0.83245
[42]	validation_0-auc:0.87824	validation_1-auc:0.83158
[43]	validation_0-auc:0.87899	validation_1-auc:0.83155
[44]	validation_0-auc:0.87987	validation_1-auc:0.83123
[45]	validation_0-auc:0.88041	validation_1-auc:0.83135
[46]	validation_0-auc:0.88118	validation_1-auc:0.83182
[47]	validation_0-auc:0.88162	validation_1-auc:0.83165
[48]	validation_0-auc:0.88223	validation_1-auc:0.83186
[49]	validation_0-auc:0.88297	validation_1-auc:0.83209
[50]	validation_0-auc:0.88386	validation_1-auc:0.83212
[51]	validation_0-auc:0.88479	validation_1-auc:0.83226
[52]	validation_0-auc:0.88530	validation_1-auc:0.83275
[53]	validation_0-auc:0.88610	validation_1-auc:0.83253
[54]	validation_0-auc:0.88655	validation_1-auc:0.83231
[55]	validation_0-auc:0.88709	validation_1-auc:0.83262
[56]	validation_0-auc:0.88765	validation_1-auc:0.83237
[57]	validation_0-auc:0.88802	validation_1-auc:0.83231
[58]	validation_0-auc:0.88860	validation_1-auc:0.83223
[59]	validation_0-auc:0.88888	validation_1-auc:0.83218
[60]	validation_0-auc:0.88939	validation_1-auc:0.83220
[61]	validation_0-auc:0.88976	validation_1-auc:0.83224
[62]	validation_0-auc:0.89017	validation_1-auc:0.83220
[63]	validation_0-auc:0.89064	validation_1-auc:0.83225
[64]	validation_0-auc:0.89091	validation_1-auc:0.83218
[65]	validation_0-auc:0.89137	validation_1-auc:0.83215
[66]	validation_0-auc:0.89202	validation_1-auc:0.83226
[67]	validation_0-auc:0.89241	validation_1-auc:0.83238
[68]	validation_0-auc:0.89268	validation_1-auc:0.83251
[69]	validation_0-auc:0.89296	validation_1-auc:0.83280
[70]	validation_0-auc:0.89314	validation_1-auc:0.83249
[71]	validation_0-auc:0.89330	validation_1-auc:0.83252
[72]	validation_0-auc:0.89354	validation_1-auc:0.83253
[73]	validation_0-auc:0.89366	validation_1-auc:0.83251
[74]	validation_0-auc:0.89399	validation_1-auc:0.83272
[75]	validation_0-auc:0.89429	validation_1-auc:0.83284
[76]	validation_0-auc:0.89442	validation_1-auc:0.83278
[77]	validation_0-auc:0.89458	validation_1-auc:0.83278
[78]	validation_0-auc:0.89489	validation_1-auc:0.83277
[79]	validation_0-auc:0.89510	validation_1-auc:0.83262
[80]	validation_0-auc:0.89528	validation_1-auc:0.83267
[81]	validation_0-auc:0.89554	validation_1-auc:0.83260
[82]	validation_0-auc:0.89572	validation_1-auc:0.83244
[83]	validation_0-auc:0.89584	validation_1-auc:0.83231
[84]	validation_0-auc:0.89609	validation_1-auc:0.83238
[85]	validation_0-auc:0.89671	validation_1-auc:0.83239
[86]	validation_0-auc:0.89694	validation_1-auc:0.83248
[87]	validation_0-auc:0.89771	validation_1-auc:0.83246
[88]	validation_0-auc:0.89777	validation_1-auc:0.83259
[89]	validation_0-auc:0.89805	validation_1-auc:0.83244
[90]	validation_0-auc:0.89859	validation_1-auc:0.83220
[91]	validation_0-auc:0.89870	validation_1-auc:0.83205
[92]	validation_0-auc:0.89880	validation_1-auc:0.83192
[93]	validation_0-auc:0.89899	validation_1-auc:0.83205
[94]	validation_0-auc:0.89904	validation_1-auc:0.83207
[95]	validation_0-auc:0.89914	validation_1-auc:0.83193
[96]	validation_0-auc:0.89925	validation_1-auc:0.83191
[97]	validation_0-auc:0.89953	validation_1-auc:0.83200
[98]	validation_0-auc:0.89995	validation_1-auc:0.83177
[99]	validation_0-auc:0.89998	validation_1-auc:0.83175
[0]	validation_0-auc:0.81645	validation_1-auc:0.80537
[1]	validation_0-auc:0.80841	validation_1-auc:0.79421
[2]	validation_0-auc:0.82421	validation_1-auc:0.81059
[3]	validation_0-auc:0.83509	validation_1-auc:0.81859
[4]	validation_0-auc:0.84064	validation_1-auc:0.82326
[5]	validation_0-auc:0.84302	validation_1-auc:0.82613
[6]	validation_0-auc:0.84507	validation_1-auc:0.82768
[7]	validation_0-auc:0.84576	validation_1-auc:0.82752
[8]	validation_0-auc:0.84711	validation_1-auc:0.82856
[9]	validation_0-auc:0.84767	validation_1-auc:0.82857
[10]	validation_0-auc:0.84926	validation_1-auc:0.82868
[11]	validation_0-auc:0.85043	validation_1-auc:0.83004
[12]	validation_0-auc:0.85111	validation_1-auc:0.82965
[13]	validation_0-auc:0.85329	validation_1-auc:0.83065
[14]	validation_0-auc:0.85445	validation_1-auc:0.83078
[15]	validation_0-auc:0.85656	validation_1-auc:0.83118
[16]	validation_0-auc:0.85793	validation_1-auc:0.83102
[17]	validation_0-auc:0.85877	validation_1-auc:0.83094
[18]	validation_0-auc:0.86007	validation_1-auc:0.83076
[19]	validation_0-auc:0.86181	validation_1-auc:0.83164
[20]	validation_0-auc:0.86247	validation_1-auc:0.83178
[21]	validation_0-auc:0.86362	validation_1-auc:0.83225
[22]	validation_0-auc:0.86460	validation_1-auc:0.83240
[23]	validation_0-auc:0.86532	validation_1-auc:0.83242
[24]	validation_0-auc:0.86581	validation_1-auc:0.83245
[25]	validation_0-auc:0.86684	validation_1-auc:0.83222
[26]	validation_0-auc:0.86742	validation_1-auc:0.83215
[27]	validation_0-auc:0.86868	validation_1-auc:0.83198
[28]	validation_0-auc:0.86982	validation_1-auc:0.83290
[29]	validation_0-auc:0.87041	validation_1-auc:0.83411
[30]	validation_0-auc:0.87087	validation_1-auc:0.83409
[31]	validation_0-auc:0.87148	validation_1-auc:0.83419
[32]	validation_0-auc:0.87207	validation_1-auc:0.83381
[33]	validation_0-auc:0.87286	validation_1-auc:0.83403
[34]	validation_0-auc:0.87358	validation_1-auc:0.83424
[35]	validation_0-auc:0.87485	validation_1-auc:0.83407
[36]	validation_0-auc:0.87534	validation_1-auc:0.83437
[37]	validation_0-auc:0.87563	validation_1-auc:0.83455
[38]	validation_0-auc:0.87629	validation_1-auc:0.83447
[39]	validation_0-auc:0.87685	validation_1-auc:0.83467
[40]	validation_0-auc:0.87778	validation_1-auc:0.83541
[41]	validation_0-auc:0.87873	validation_1-auc:0.83567
[42]	validation_0-auc:0.87908	validation_1-auc:0.83615
[43]	validation_0-auc:0.87978	validation_1-auc:0.83653
[44]	validation_0-auc:0.88076	validation_1-auc:0.83637
[45]	validation_0-auc:0.88191	validation_1-auc:0.83653
[46]	validation_0-auc:0.88301	validation_1-auc:0.83619
[47]	validation_0-auc:0.88385	validation_1-auc:0.83652
[48]	validation_0-auc:0.88438	validation_1-auc:0.83662
[49]	validation_0-auc:0.88498	validation_1-auc:0.83696
[50]	validation_0-auc:0.88597	validation_1-auc:0.83648
[51]	validation_0-auc:0.88648	validation_1-auc:0.83670
[52]	validation_0-auc:0.88703	validation_1-auc:0.83700
[53]	validation_0-auc:0.88722	validation_1-auc:0.83677
[54]	validation_0-auc:0.88748	validation_1-auc:0.83688
[55]	validation_0-auc:0.88805	validation_1-auc:0.83688
[56]	validation_0-auc:0.88884	validation_1-auc:0.83675
[57]	validation_0-auc:0.88931	validation_1-auc:0.83680
[58]	validation_0-auc:0.88980	validation_1-auc:0.83719
[59]	validation_0-auc:0.89012	validation_1-auc:0.83726
[60]	validation_0-auc:0.89058	validation_1-auc:0.83749
[61]	validation_0-auc:0.89137	validation_1-auc:0.83754
[62]	validation_0-auc:0.89161	validation_1-auc:0.83735
[63]	validation_0-auc:0.89228	validation_1-auc:0.83730
[64]	validation_0-auc:0.89276	validation_1-auc:0.83713
[65]	validation_0-auc:0.89325	validation_1-auc:0.83690
[66]	validation_0-auc:0.89383	validation_1-auc:0.83674
[67]	validation_0-auc:0.89419	validation_1-auc:0.83681
[68]	validation_0-auc:0.89436	validation_1-auc:0.83690
[69]	validation_0-auc:0.89473	validation_1-auc:0.83692
[70]	validation_0-auc:0.89504	validation_1-auc:0.83678
[71]	validation_0-auc:0.89525	validation_1-auc:0.83681
[72]	validation_0-auc:0.89576	validation_1-auc:0.83672
[73]	validation_0-auc:0.89612	validation_1-auc:0.83654
[74]	validation_0-auc:0.89629	validation_1-auc:0.83664
[75]	validation_0-auc:0.89668	validation_1-auc:0.83648
[76]	validation_0-auc:0.89704	validation_1-auc:0.83642
[77]	validation_0-auc:0.89744	validation_1-auc:0.83647
[78]	validation_0-auc:0.89762	validation_1-auc:0.83653
[79]	validation_0-auc:0.89828	validation_1-auc:0.83634
[80]	validation_0-auc:0.89850	validation_1-auc:0.83616
[81]	validation_0-auc:0.89905	validation_1-auc:0.83612
[82]	validation_0-auc:0.89919	validation_1-auc:0.83615
[83]	validation_0-auc:0.89941	validation_1-auc:0.83605
[84]	validation_0-auc:0.89957	validation_1-auc:0.83597
[85]	validation_0-auc:0.89985	validation_1-auc:0.83590
[86]	validation_0-auc:0.90013	validation_1-auc:0.83573
[87]	validation_0-auc:0.90027	validation_1-auc:0.83583
[88]	validation_0-auc:0.90049	validation_1-auc:0.83583
[89]	validation_0-auc:0.90105	validation_1-auc:0.83591
[90]	validation_0-auc:0.90137	validation_1-auc:0.83603
[0]	validation_0-auc:0.82735	validation_1-auc:0.81086
[1]	validation_0-auc:0.82093	validation_1-auc:0.80133
[2]	validation_0-auc:0.83454	validation_1-auc:0.81412
[3]	validation_0-auc:0.83914	validation_1-auc:0.81722
[4]	validation_0-auc:0.84088	validation_1-auc:0.81769
[5]	validation_0-auc:0.84242	validation_1-auc:0.81829
[6]	validation_0-auc:0.84389	validation_1-auc:0.82037
[7]	validation_0-auc:0.84522	validation_1-auc:0.82200
[8]	validation_0-auc:0.84807	validation_1-auc:0.82357
[9]	validation_0-auc:0.84943	validation_1-auc:0.82381
[10]	validation_0-auc:0.84973	validation_1-auc:0.82356
[11]	validation_0-auc:0.85210	validation_1-auc:0.82542
[12]	validation_0-auc:0.85321	validation_1-auc:0.82615
[13]	validation_0-auc:0.85385	validation_1-auc:0.82603
[14]	validation_0-auc:0.85490	validation_1-auc:0.82635
[15]	validation_0-auc:0.85742	validation_1-auc:0.82812
[16]	validation_0-auc:0.85836	validation_1-auc:0.82840
[17]	validation_0-auc:0.85897	validation_1-auc:0.82852
[18]	validation_0-auc:0.85940	validation_1-auc:0.82866
[19]	validation_0-auc:0.86035	validation_1-auc:0.82964
[20]	validation_0-auc:0.86207	validation_1-auc:0.83053
[21]	validation_0-auc:0.86343	validation_1-auc:0.83002
[22]	validation_0-auc:0.86528	validation_1-auc:0.83115
[23]	validation_0-auc:0.86568	validation_1-auc:0.83152
[24]	validation_0-auc:0.86640	validation_1-auc:0.83166
[25]	validation_0-auc:0.86677	validation_1-auc:0.83190
[26]	validation_0-auc:0.86697	validation_1-auc:0.83271
[27]	validation_0-auc:0.86818	validation_1-auc:0.83328
[28]	validation_0-auc:0.86887	validation_1-auc:0.83358
[29]	validation_0-auc:0.86908	validation_1-auc:0.83352
[30]	validation_0-auc:0.87045	validation_1-auc:0.83422
[31]	validation_0-auc:0.87145	validation_1-auc:0.83413
[32]	validation_0-auc:0.87246	validation_1-auc:0.83441
[33]	validation_0-auc:0.87314	validation_1-auc:0.83443
[34]	validation_0-auc:0.87407	validation_1-auc:0.83453
[35]	validation_0-auc:0.87487	validation_1-auc:0.83466
[36]	validation_0-auc:0.87558	validation_1-auc:0.83466
[37]	validation_0-auc:0.87663	validation_1-auc:0.83505
[38]	validation_0-auc:0.87747	validation_1-auc:0.83420
[39]	validation_0-auc:0.87857	validation_1-auc:0.83427
[40]	validation_0-auc:0.87941	validation_1-auc:0.83466
[41]	validation_0-auc:0.88040	validation_1-auc:0.83513
[42]	validation_0-auc:0.88109	validation_1-auc:0.83526
[43]	validation_0-auc:0.88225	validation_1-auc:0.83570
[44]	validation_0-auc:0.88264	validation_1-auc:0.83594
[45]	validation_0-auc:0.88321	validation_1-auc:0.83598
[46]	validation_0-auc:0.88432	validation_1-auc:0.83602
[47]	validation_0-auc:0.88465	validation_1-auc:0.83612
[48]	validation_0-auc:0.88558	validation_1-auc:0.83607
[49]	validation_0-auc:0.88625	validation_1-auc:0.83597
[50]	validation_0-auc:0.88686	validation_1-auc:0.83582
[51]	validation_0-auc:0.88742	validation_1-auc:0.83586
[52]	validation_0-auc:0.88806	validation_1-auc:0.83642
[53]	validation_0-auc:0.88850	validation_1-auc:0.83674
[54]	validation_0-auc:0.88903	validation_1-auc:0.83683
[55]	validation_0-auc:0.88934	validation_1-auc:0.83712
[56]	validation_0-auc:0.89023	validation_1-auc:0.83709
[57]	validation_0-auc:0.89075	validation_1-auc:0.83728
[58]	validation_0-auc:0.89103	validation_1-auc:0.83731
[59]	validation_0-auc:0.89142	validation_1-auc:0.83743
[60]	validation_0-auc:0.89182	validation_1-auc:0.83761
[61]	validation_0-auc:0.89208	validation_1-auc:0.83735
[62]	validation_0-auc:0.89253	validation_1-auc:0.83732
[63]	validation_0-auc:0.89280	validation_1-auc:0.83741
[64]	validation_0-auc:0.89345	validation_1-auc:0.83764
[65]	validation_0-auc:0.89405	validation_1-auc:0.83762
[66]	validation_0-auc:0.89422	validation_1-auc:0.83757
[67]	validation_0-auc:0.89442	validation_1-auc:0.83766
[68]	validation_0-auc:0.89481	validation_1-auc:0.83782
[69]	validation_0-auc:0.89513	validation_1-auc:0.83799
[70]	validation_0-auc:0.89531	validation_1-auc:0.83802
[71]	validation_0-auc:0.89565	validation_1-auc:0.83815
[72]	validation_0-auc:0.89587	validation_1-auc:0.83818
[73]	validation_0-auc:0.89640	validation_1-auc:0.83786
[74]	validation_0-auc:0.89664	validation_1-auc:0.83795
[75]	validation_0-auc:0.89688	validation_1-auc:0.83800
[76]	validation_0-auc:0.89715	validation_1-auc:0.83811
[77]	validation_0-auc:0.89738	validation_1-auc:0.83818
[78]	validation_0-auc:0.89756	validation_1-auc:0.83817
[79]	validation_0-auc:0.89778	validation_1-auc:0.83840
[80]	validation_0-auc:0.89799	validation_1-auc:0.83838
[81]	validation_0-auc:0.89809	validation_1-auc:0.83846
[82]	validation_0-auc:0.89872	validation_1-auc:0.83860
[83]	validation_0-auc:0.89902	validation_1-auc:0.83847
[84]	validation_0-auc:0.89920	validation_1-auc:0.83847
[85]	validation_0-auc:0.89983	validation_1-auc:0.83865
[86]	validation_0-auc:0.90012	validation_1-auc:0.83877
[87]	validation_0-auc:0.90046	validation_1-auc:0.83896
[88]	validation_0-auc:0.90051	validation_1-auc:0.83901
[89]	validation_0-auc:0.90057	validation_1-auc:0.83889
[90]	validation_0-auc:0.90077	validation_1-auc:0.83891
[91]	validation_0-auc:0.90091	validation_1-auc:0.83890
[92]	validation_0-auc:0.90105	validation_1-auc:0.83892
[93]	validation_0-auc:0.90120	validation_1-auc:0.83893
[94]	validation_0-auc:0.90130	validation_1-auc:0.83898
[95]	validation_0-auc:0.90147	validation_1-auc:0.83894
[96]	validation_0-auc:0.90218	validation_1-auc:0.83897
[97]	validation_0-auc:0.90230	validation_1-auc:0.83902
[98]	validation_0-auc:0.90248	validation_1-auc:0.83894
[99]	validation_0-auc:0.90263	validation_1-auc:0.83884
[0]	validation_0-auc:0.82825	validation_1-auc:0.80009
[1]	validation_0-auc:0.82290	validation_1-auc:0.79276
[2]	validation_0-auc:0.83493	validation_1-auc:0.80180
[3]	validation_0-auc:0.83857	validation_1-auc:0.80600
[4]	validation_0-auc:0.84348	validation_1-auc:0.80991
[5]	validation_0-auc:0.84459	validation_1-auc:0.80746
[6]	validation_0-auc:0.84824	validation_1-auc:0.80970
[7]	validation_0-auc:0.85110	validation_1-auc:0.81288
[8]	validation_0-auc:0.85252	validation_1-auc:0.81518
[9]	validation_0-auc:0.85681	validation_1-auc:0.81610
[10]	validation_0-auc:0.85429	validation_1-auc:0.81511
[11]	validation_0-auc:0.85779	validation_1-auc:0.81792
[12]	validation_0-auc:0.85992	validation_1-auc:0.81980
[13]	validation_0-auc:0.86127	validation_1-auc:0.81878
[14]	validation_0-auc:0.86355	validation_1-auc:0.82074
[15]	validation_0-auc:0.86211	validation_1-auc:0.81858
[16]	validation_0-auc:0.86242	validation_1-auc:0.81627
[17]	validation_0-auc:0.86272	validation_1-auc:0.81555
[18]	validation_0-auc:0.86526	validation_1-auc:0.81783
[19]	validation_0-auc:0.86938	validation_1-auc:0.81966
[20]	validation_0-auc:0.87277	validation_1-auc:0.82183
[21]	validation_0-auc:0.87221	validation_1-auc:0.82025
[22]	validation_0-auc:0.87500	validation_1-auc:0.82185
[23]	validation_0-auc:0.87555	validation_1-auc:0.82284
[24]	validation_0-auc:0.87621	validation_1-auc:0.82226
[25]	validation_0-auc:0.87843	validation_1-auc:0.82376
[26]	validation_0-auc:0.88051	validation_1-auc:0.82485
[27]	validation_0-auc:0.88142	validation_1-auc:0.82452
[28]	validation_0-auc:0.88247	validation_1-auc:0.82341
[29]	validation_0-auc:0.88362	validation_1-auc:0.82462
[30]	validation_0-auc:0.88435	validation_1-auc:0.82566
[31]	validation_0-auc:0.88484	validation_1-auc:0.82432
[32]	validation_0-auc:0.88540	validation_1-auc:0.82245
[33]	validation_0-auc:0.88694	validation_1-auc:0.82341
[34]	validation_0-auc:0.88761	validation_1-auc:0.82263
[35]	validation_0-auc:0.88776	validation_1-auc:0.82136
[36]	validation_0-auc:0.88896	validation_1-auc:0.82286
[37]	validation_0-auc:0.88887	validation_1-auc:0.82213
[38]	validation_0-auc:0.88901	validation_1-auc:0.82142
[39]	validation_0-auc:0.88881	validation_1-auc:0.82080
[40]	validation_0-auc:0.89081	validation_1-auc:0.82302
[41]	validation_0-auc:0.89316	validation_1-auc:0.82464
[42]	validation_0-auc:0.89403	validation_1-auc:0.82586
[43]	validation_0-auc:0.89601	validation_1-auc:0.82714
[44]	validation_0-auc:0.89737	validation_1-auc:0.82706
[45]	validation_0-auc:0.89888	validation_1-auc:0.82811
[46]	validation_0-auc:0.89869	validation_1-auc:0.82768
[47]	validation_0-auc:0.89964	validation_1-auc:0.82845
[48]	validation_0-auc:0.90040	validation_1-auc:0.82932
[49]	validation_0-auc:0.90137	validation_1-auc:0.83005
[50]	validation_0-auc:0.90169	validation_1-auc:0.82927
[51]	validation_0-auc:0.90282	validation_1-auc:0.83004
[52]	validation_0-auc:0.90359	validation_1-auc:0.83045
[53]	validation_0-auc:0.90520	validation_1-auc:0.83097
[54]	validation_0-auc:0.90552	validation_1-auc:0.83111
[55]	validation_0-auc:0.90634	validation_1-auc:0.83159
[56]	validation_0-auc:0.90699	validation_1-auc:0.83111
[57]	validation_0-auc:0.90715	validation_1-auc:0.83111
[58]	validation_0-auc:0.90784	validation_1-auc:0.83180
[59]	validation_0-auc:0.90835	validation_1-auc:0.83202
[60]	validation_0-auc:0.90899	validation_1-auc:0.83202
[61]	validation_0-auc:0.90931	validation_1-auc:0.83141
[62]	validation_0-auc:0.91019	validation_1-auc:0.83165
[63]	validation_0-auc:0.91112	validation_1-auc:0.83111
[64]	validation_0-auc:0.91139	validation_1-auc:0.83084
[65]	validation_0-auc:0.91245	validation_1-auc:0.83098
[66]	validation_0-auc:0.91319	validation_1-auc:0.83034
[67]	validation_0-auc:0.91346	validation_1-auc:0.83064
[68]	validation_0-auc:0.91385	validation_1-auc:0.83038
[69]	validation_0-auc:0.91432	validation_1-auc:0.83030
[70]	validation_0-auc:0.91516	validation_1-auc:0.83055
[71]	validation_0-auc:0.91552	validation_1-auc:0.83092
[72]	validation_0-auc:0.91552	validation_1-auc:0.83065

In [ ]:
# n_estimators를 500 증가 후 최적으로 찾은 하이퍼 파라미터를 기반으로 학습과 예측 수행
xgb_clf = XGBClassifier(n_estimators=500, learning_rate=round(best['learning_rate'], 5),
                        max_depth=int(best['max_depth']),
                        min_child_weight=int(best['min_child_weight']),
                        colsample_bytree=round(best['colsample.bytree'], 5)
                        )
# evaluation metric을 auc로, early stopping은 100으로 설정하고 학습 수행
xgb_clf.fit(X_tr, y_tr, early_stopping_rounds=100,
            eval_metric="auc",eval_set=[(X_tr, y_tr), (X_val, y_val)])

xgb_roc_score = roc_auc_score(y_test, xgb_clf.predict_proba(X_test)[:,1 ])
print('ROC AUC: {0:.4f}'.format(xgb_roc_score))

ROC—AUC가 이전 예제의 0.8429에서 하이퍼 파라미터 튜닝 이후 0.8457로 개선됨.

시간을 투자한 것만큼은 아닐 수 있으나 캐글과 같이 치열한 순위 경쟁이 필요한 경우에 이 정도의 수치 개선은 도움이 될 수 있음

한 가지 아쉬운 점은 XGBoost가 GBM보다는 빠르지만 아무래도 GBM을 기반으로 하고 있기 때문에 수행 시간이 상당히 더 많이 요구됨

앙상블 계열 알고리즘에서 하이퍼 파라미터 튜닝으로 성능 수치 개선이 급격하게 되는 경우는 많지 않음 -> 앙상블 계열 알고리즘은 과적합이나 잡음에 기본적으로 뛰어난 알고리즘이기 때문

In [ ]:
from xgboost import plot_importance
import matplotlib.pyplot as plt
%matplotlib inline

fig, ax = plt.subplots(1,1,figsize=(10,8))
plot_importance(xgb_clf, ax=ax , max_num_features=20,height=0.4)

### 3) LightGBM 모델 학습과 하이퍼 파라미터 튜닝

In [ ]:
from lightgbm import LGBMClassifier
from lightgbm import early_stopping ### 추가 ###

lgbm_clf = LGBMClassifier(n_estimators=500)

eval_set=[(X_tr, y_tr), (X_val, y_val)]
lgbm_clf.fit(X_tr, y_tr,
             eval_metric="auc", eval_set=eval_set,
             callbacks=[early_stopping(stopping_rounds=100)]) ### 추가###

lgbm_roc_score = roc_auc_score(y_test, lgbm_clf.predict_proba(X_test)[:,1 ])
print('ROC AUC:{0:.4f}'.format(lgbm_roc_score))

LightGBM을 직접 수행해 보면 XGBoost보다 학습에 걸리는 시간이 좀 더 단축됐음을 느낄 수 있음

In [ ]:
lgbm_search_space = {'num_leaves': hp.quniform('numjeaves', 32, 64, 1),
                     'max_depth': hp.quniform('max_depth', 100, 160, 1 ),
                     'min_child_samples' : hp.quniform('min_child_samples', 60, 100, 1),
                     'subsample': hp.uniform('subsample', 0.7, 1),
                     'learning_rate' : hp.uniform('learning_rate', 0.01, 0.2)
                     }

def objective_func(search_space):
  lgbm_clf = LGBMClassifier(n_estimators=100,
                            num_leaves=int(search_space['num_leaves']),
                            max_depth=int(search_space['max_depth']),
                            min_child_samples=int(search_space['min_child_samples']),
                            subsample=search_space['subsample'],
                            learning_rate=search_space['learning_rate'])
  # 3개 k-fold 방식으로 평가된 roc_auc 지표를 담는 list
  roc_auc_list = []

  # 3개 k-fold 방식 적용
  kf = KFold(n_splits=3)
  # X_train을 다시 학습과 검증용 데이터로 분리
  for tr_index, val_index in kf.split(X_train):
    # kf .split(X_train)으로 추출된 학습과 검증 index 값으로 학습과 검증 데이터 세트 분리
    X_tr, y_tr = X_train.iloc[tr_index], y_train.iloc[tr_index]
    X_val, y_val = X_train.iloc[val_index], y_train.iloc[val_index]

    # early stopping은 30회로 설정하고 추출된 학습과 검증 데이터로 XGBClassifier 학습 수행.
    lgbm_clf.fit(X_tr, y_tr,
                 eval_metric="auc",
                 eval_set=[(X_tr, y_tr), (X_val, y_val)],
                 callbacks=[early_stopping(stopping_rounds=30)]) ### 추가 ###

    # 1 로 예측한 확률값 추출 후 roc auc 계산하고 평균 roc auc 계산을 위해 list에 결괏값 담음.
    score = roc_auc_score(y_val, lgbm_clf.predict_proba(X_val)[:, 1])
    roc_auc_list.append(score)

  # 3개 k-fold로 계산된 roc_auc 값의 평균값을 반환하되,
  # HyperOpt는 목적함수의 최솟값을 위한 입력값을 찾으므로 -1을 곱한 뒤 반환.
  return -1*np.mean(roc_auc_list)

In [ ]:
from hyperopt import fmin, tpe, Trials

trials = Trials()

# fmin() 함수를 호출. max_evals 지정된 횟수만큼 반복 후 목적함수의 최솟값을 가지는 최적 입력값 추출.
best = fmin(fn=objective_func, space=lgbm_search_space, algo=tpe.suggest,
            max_evals=50, # 최대 반복 횟수를 지정합니다.
            trials=trials, rstate=np.random.default_rng(seed=30))

print('best:', best)

In [ ]:
lgbm_clf = LGBMClassifier(n_estimators=500, num_leaves=int(best['num_leaves']),
                          max_depth=int(best['max_depth']),
                          min_child_samples=int(best['min_child_samples']),
                          subsample=round(best['subsample'], 5),
                          learning_rate=round(best['learning_rate'], 5)
                          )

# evaluation metric을 auc로, early stopping은 100으로 설정하고 학습 수행.
lgbm_clf.fit(X_tr, y_tr, early_stopping_rounds=100,
             evaljnetric="auc",eval_set=[(X_tr, y_tr), (X_val, y_val)])

lgbm_roc_score = roc_auc_score(y_test, xgb_clf.predict_proba(X_test)[:,1 ])
print('ROC AUC:{0:.4f}'.format(lgbm_roc_score))

LightGBM의 경우 학습 시간이 상대적으로 빠르기 때문에 위에 기술된 하이퍼 파라미터 외에 추가적인 하이퍼 파라미터를 적용해서 튜닝을 수행해 보는 것도 좋음

## 10. 분류 실습 - 캐글 신용카드 사기 검출

해당 데이터 세트의 레이블인 Class 속성은 매우 불균형한 분포를 가지고 있음

Class는 0과 1로 분류되는데 0이 사기가 아닌 정상적인 신용카드 트랜잭션 데이터, 1은 신용카드 사기 트랜잭션을 의미

전체 데이터의 약 0.172%만이 레이블 값이 1, 즉 사기 트랜잭션.

일반적으로 사기 검출(Fraud Detection)이나 이상 검출(Anomaly Detection)과 같은 데이터 세트는 이처럼 레이블 값이 극도로 불균형한 분포를 가지기 쉬움 -> 사기와 같은 이상 현상은 전체 데이터에서 차지하는 비중이 매우 적을 수밖에 없기 때문

### 1) 언더 샘플링과 오버 샘플링의 이해

이상 레이블을 가지는 데이터 건수는 매우 적기 때문에 제대로 다양한 유형을 학습하지 못하는 반면에 정상 레이블을 가지는 데이터 건수는 매우 많기 때문에 일방적으로 정상 레이블로 치우친 학습을 수행해 제대로 된 이상 데이터 검출이 어려워지기 쉬움

지도학습에서 극도로 불균형한 레이블 값 분포로 인한 문제점을 해결하기 위해서는 적절한 학습 데이터를 확보하는 방안이 필요한데,

대표적으로 **오버 샘플링(Oversampling)**과 **언더 샘플링(Undersampling)** 방법이 있으며, 오버 샘플링 방식이 예측 성능상 조금 유리한 경우가 많아 상대적으로 더 많이 사용됨

언더 샘플링 : 많은 데이터 세트를 적은 데이터 세트 수준으로 감소시키는 방식. 즉, 정상 레이블을 가진 데이터가
10,000건, 이상 레이블을 가진 데이터가 100건이 있으면 정상 레이블 데이터를 100건으로 줄여 버리는 방식

- 정상 레이블 데이터를 이상 레이블 데이터 수준으로 줄여 버린 상태에서 학습을 수행하면 과도하게 정상 레이블로 학
습/예측하는 부작용을 개선할 수 있음

- 너무 많은 정상 레이블 데이터를 감소시켜서 정상 레이블의 경우 제대로 된 학습을 수행할 수 없는 문제가 발생할 수도 있음

오버 샘플링 : 이상 데이터와 같이 적은 데이터 세트를 증식하여 학습을 위한 충분한 데이터를 확보하는 방법.

- 동일한 데이터를 단순히 증식하는 방법은 과적합(Overfitting)이 되기 때문에 의미가 없으므로 원본 데이터의 피처 값들을 아주 약간만 변경하여 증식함. 대표적으로 SMOTE(Synthetic Minority Over-sampling Technique) 방법이 있음

- SMOTE는 적은 데이터 세트에 있는 개별 데이터들의 K 최근접 이웃(K Nearest Neighbor)을 찾아서 이 데이터와 K개
이웃들의 차이를 일정 값으로 만들어서 기존 데이터와 약간 차이가 나는 새로운 데이터들을 생성하는 방식

In [ ]:
!pip install imbalanced-learn
# conda install -c conda-forge imbalanced-learn

### 2) 데이터 일차 가공 및 모델 학습/예측/평가

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pit
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline
card_df = pd.read_csv('/content/drive/MyDrive/YB_data/creditcard.csv')
card_df.head(3)

In [ ]:
from sklearn.model_selection import train_test_split

# 인자로 입력받은 DataFrame을 복사한 뒤 Time 칼럼만 삭제하고 복사된 DataFrame 반환
def get_preprocessed_df(df=None):
  df_copy = df .copy()
  df_copy.drop('Time', axis=1, inplace=True)
  return df_copy

In [ ]:
# 사전 데이터 가공 후 학습과 테스트 데이터 세트를 반환하는 함수.
def get_train_test_dataset(df=None):
  # 인자로 입력된 DataFrame의 사전 데이터 가공이 완료된 복사 DataFrame 반환
  df_copy = get_preprocessed_df(df)
  # DataFrame의 맨 마지막 칼럼이 레이블, 나머지는 피처들
  X_features = df_copy.iloc[:, :-1]
  y_target = df_copy.iloc[:, -1]
  # train_test_split( )으로 학습과 테스트 데이터 분할. stratify=y_target으로 Stratified 기반 분할
  X_train, X_test, y_train, y_test = \
  train_test_split(X_features, y_target, test_size=0.3,
                   random_state=0, stratify=y_target)
  # 학습과 테스트 데이터 세트 반환
  return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = get_train_test_dataset(card_df)

In [ ]:
print('학습 데이터 레이블 값 비율')
print(y_train.value_counts()/y_train.shape[0] * 100)
print('테스트 데이터 레이블 값 비율')
print(y_test.value_counts()/y_test.shape[0] * 100)

In [ ]:
### 추가 ###
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score,recall_score, f1_score, roc_auc_score

def get_clf_eval(y_test, pred=None, pred_proba=None):
  confusion = confusion_matrix(y_test, pred)
  accuracy = accuracy_score(y_test , pred)
  precision = precision_score(y_test , pred)
  recall = recall_score(y_test , pred)
  f1 = f1_score(y_test,pred)

  # ROC-AUC 추가
  roc_auc = roc_auc_score(y_test, pred_proba)
  print('오차 행렬')
  print(confusion)

  # ROC-AUC print 추가
  print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}, F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

In [ ]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression(max_iter=1000)
lr_clf.fit(X_train, y_train)
lr_pred = lr_clf.predict(X_test)
lr_pred_proba = lr_clf.predict_proba(X_test)[:, 1]

# 3장에서 사용한 get_clf_eval() 함수를 이용해 평가 수행.
get_clf_eval(y_test, lr_pred, lr_pred_proba)

In [ ]:
# 인자로 사이킷런의 Estimator 객체와 학습/테스트 데이터 세트를 입력받아서 학습/예측/평가 수행.
def get_model_train_eval(model, ftr_train=None, ftr_test=None, tgt_train=None, tgt_test=None):
  model.fit(ftr_train, tgt_train)
  pred = model.predict(ftr_test)
  pred_proba = model.predict_proba(ftr_test)[:, 1]
  get_clf_eval(tgt_test, pred, pred_proba)

In [ ]:
from lightgbm import LGBMClassifier

lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
get_model_train_eval(lgbm_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

### 3) 데이터 분포도 변환 후 모델 학습/예측/평가

In [ ]:
import seaborn as sns

plt.figure(figsize=(8, 4))
plt.xticks(range(0, 30000, 1000), rotation=60)
sns.histplot(card_df['Amount'], bins=100, kde=True)
plt.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
# 사이킷런의 StandardScaler를 이용해 정규 분포 형태로 Amount 피처값 변환하는 로직으로 수정.
def get_preprocessed_df(df=None):
  df_copy = df.copy()
  scaler = StandardScaler()
  amount_n = scaler.fit_transform(df_copy['Amount'].values.reshape(-1, 1))
  # 변환된 Amount를 Amount_Scaled로 피처명 변경후 DataFrame맨 앞 칼럼으로 입력
  df_copy.insert(0, 'Amount—Scaled', amount_n)
  # 기존 Time, Amount 피처 삭제
  df_copy.drop(['Time', 'Amount'], axis=1, inplace=True)
  return df_copy

In [ ]:
# Amount를 정규 분포 형태로 변환 후 로지스틱 회귀 및 LightGBM 수행.
X_train, X_test, y_train, y_test = get_train_test_dataset(card_df)

print('### 로지스틱 회귀 예측 성능 ###')
lr_clf = LogisticRegression(max_iter=1000)
get_model_train_eval(lr_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

print('### LightGBM 예측 성능 ###')
lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
get_model_train_eval(lgbm_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

정규 분포 형태로 Amount 피처값을 변환한 후 테스트 데이터 세트에 적용한 로지스틱 회귀의 경우는 정밀도와 재현율이 오히려 조금 저하되었고, LightGBM의 경우는 약간 정밀도와 재현율이 저하되었지만 큰 성능상의 변경은 없음

In [ ]:
def get_preprocessed_df(df=None):
  df_copy = df.copy()
  # 넘파이의 log1p( )를 이용해 Amount를 로그 변환
  amount_n = np.log1p(df_copy['Amount'])
  df_copy.insert(0, 'Amount_Scaled', amount_n)
  df_copy.drop(['Time', 'Amount'], axis=1, inplace=True)
  return df_copy

In [ ]:
X_train, X_test, y_train, y_test = get_train_test_dataset(card_df)

print('### 로지스틱 회귀 예측 성능 ###')
get_model_train_eval(lr_clf, ftr_train=X_train, ftr_test=X_test,
                     tgt_train=y_train, tgt_test=y_test)

print('### LightGBM 예측 성능 ###')
get_model_train_eval(lgbm_clf, ftr_train=X_train, ftr_test=X_test,
                     tgt_train=y_train, tgt_test=y_test)

로지스틱 회귀의 경우 원본 데이터 대비 정밀도는 향상되었지만 재현율은 저하되었음. LightGBM 의 경우 재현율이 향상되었음

레이블이 극도로 불균일한 데이터 세트에서 로지스틱 회귀는 데이터 변환 시 약간은 불안정한 성능 결과를 보여 주고 있음

### 4) 이상치 데이터 제거 후 모델 학습/예측/평가

이상치 데이터(Outlier)는 전체 데이터의 패턴에서 벗어난 이상 값을 가진 데이터이며, 아웃라이어라고도 불림

이상치로 인해 머신러닝 모델의 성능에 영향을 받는 경우가 발생하기 쉬움

이상치를 찾는 방법 : IQR(Inter Quantile Range) 방식

-  IQR : 사분위(Quantile) 값의 편차를 이용하는 기법으로 흔히 박스 플롯(Box Plot) 방식으로 시각화할 수 있음


이상치 데이터를 IQR을 이용해 제거 => 어떤 피처의 이상치 데이터를 검출할 것인지 선택 필요

- 매우 많은 피처가 있을 경우, 이들 중 결정값(즉 레이블)과 가장 상관성이 높은 피처들을 위주로 이상치를 검출하는 것이 좋음 -> 모든 피처들의 이상치를 검출하는 것은 시간이
많이 소모되며, 결정값과 상관성이 높지 않은 피처들의 경우는 이상치를 제거하더라도 크게 성능 향상에 기여하지 않기 때문

In [ ]:
import seaborn as sns

plt.figure(figsize=(9,9))
corr = card_df.corr()
sns.heatmap(corr, cmap='RdBu')

In [ ]:
import numpy as np

def get_outlier(df=None, column=None, weight=1.5):
  # fraud에 해당하는 column 데이터만 추출, 1/4 분위와 3/4 분위 지점을 np.percentile로 구항.
  fraud = df[df['Class']==1 ] [column]
  quantile_25 = np.percentile(fraud.values, 25)
  quantile_75 = np.percentile(fraud.values, 75)
  # IQR을 구하고, IQR에 1.5를 곱해 최댓값과 최솟값 지점 구함.
  iqr = quantile_75 - quantile_25
  iqr_weight = iqr * weight
  lowest_val = quantile_25 - iqr_weight
  highest_val = quantile_75 + iqr_weight
  # 최댓값보다 크거나, 최솟값보다 작은 값을 이상치 데이터로 설정하고 DataFrame index 반환.
  outlier_index = fraud[(fraud < lowest_val) | (fraud > highest_val)].index
  return outlier_index

In [ ]:
outlier_index = get_outlier(df=card_df, column='V14', weight=1.5)
print('이상치 데이터 인덱스:', outlier_index)

In [ ]:
# get_processed_df( )를 로그 변환 후 V14 피처의 이상치 데이터를 삭제하는 로직으로 변경.
def get_preprocessed_df(df=None):
  df_copy = df.copy()
  amount_n = np.log1p(df_copy['Amount'])
  df_copy.insert(0, 'Amount_Scaled', amount_n)
  df_copy.drop(['Time', 'Amount'], axis=1, inplace=True)
  # 이상치 데이터 삭제하는 로직 추가
  outlier_index = get_outlier(df=df_copy, column='V14', weight=1.5)
  df_copy.drop(outlier_index, axis=0, inplace=True)
  return df_copy

X_train, X_test, y_train, y_test = get_train_test_dataset(card_df)
print('### 로지스틱 회귀 예측 성능 ###')
get_model_train_eval(lr_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train,
                     tgt_test=y_test)
print('### LightGBM 예측 성능 ###')
get_model_train_eval(lgbm_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

### 5) SMOTE 오버 샘플링 적용 후 모델 학습/예측/평가

SMOTE를 적용할 때는 반드시 학습 데이터 세트만 오버 샘플링을 해야 함

검증 데이터 세트나 테스트 데이터 세트를 오버 샘플링할 경우 결국은 원본 데이터 세트가 아닌 데이터 세트에서 검증 또는 테스트를 수행하기 때문에 올바른 검증/테스트가 될 수 없음

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=0)
X_train_over, y_train_over = smote.fit_resample(X_train, y_train)
print ('SMOTE 적용 전 학습용 피처/레이블 데이터 세트: ', X_train.shape, y_train.shape)
print ('SMOTE 적용 후 학습용 피처/레이블 데이터 세트: ', X_train_over.shape, y_train_over.shape)
print('SMOTE 적용 후 레이블 값 분포: \n', pd.Series(y_train_over).value_counts())

In [ ]:
lr_clf = LogisticRegression(max_iter=1000)
# ftr_train과 tgt_train 인자값이 SMOTE 증식된 X_train_over와 y_train_over로 변경됨에 유의
get_model_train_eval(lr_clf, ftr_train=X_train_over, ftr_test=X_test, tgt_train=y_train_over,
                     tgt_test=y_test)

로지스틱 회귀 모델의 경우 SMOTE로 오버 샘플링된 데이터로 학습할 경우 재현율이 92.47%로 크게 증가하지만, 반대로 정밀도가 5.4%로 급격하게 저하됨

-> 재현율이 높더라도 이 정도로 저조한 정밀도로는 현실 업무에 적용할 수 없음

로지스틱 회귀 모델이 오버 샘플링으로 인해 실제 원본 데이터의 유형보다 너무나 많은 Class=1 데이터를 학습하면서 실제 테스트 데이터 세트에서 예측을 지나치게 Class=l로 적용해 정밀도가 급격히 떨어지게 된 것

In [ ]:
### 추가 ###
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from sklearn.metrics import precision_recall_curve
%matplotlib inline

def precision_recall_curve_plot(y_test , pred_proba_c1):
  # threshold ndarray와 이 threshold에 따른 정밀도, 재현율 ndarray 추출.
  precisions, recalls, thresholds = precision_recall_curve( y_test, pred_proba_c1)

  # X축을 threshold값으로, Y축은 정밀도, 재현율 값으로 각각 Plot 수행. 정밀도는 점선으로 표시
  plt.figure(figsize=(8,6))
  threshold_boundary = thresholds.shape[0]
  plt.plot(thresholds, precisions[0:threshold_boundary], linestyle='--', label='precision')
  plt.plot(thresholds, recalls[0:threshold_boundary],label='recall')

  # threshold 값 X 축의 Scale을 0.1 단위로 변경
  start, end = plt.xlim()
  plt.xticks(np.round(np.arange(start, end, 0.1),2))

  # x축, y축 label과 legend, 그리고 grid 설정
  plt.xlabel('Threshold value'); plt.ylabel('Precision and Recall value')
  plt.legend(); plt.grid()
  plt.show()

In [ ]:
precision_recall_curve_plot( y_test, lr_clf.predict_proba(X_test)[:,1])

임계값이 0.99 이하에서는 재현율이 매우 좋고 정밀도가 극단적으로 낮다가 0.99 이상에서는 반대로 재현율이 대폭 떨어지고 정밀도가 높아짐

분류 결정 임계값을 조정하더라도 임계값의 민감도가
너무 심해 올바른 재현율/정밀도 성능을 얻을 수 없으므로 로지스틱 회귀 모델의 경우 SMOTE 적용 후 올바른 예측 모델이 생성되지 못했음

In [ ]:
lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
get_model_train_eval(lgbm_clf, ftr_train=X_train_over, ftr_test=X_test,
                     tgt_train=y_train_over, tgt_test=y_test)

SMOTE를 적용하면 재현율은 높아지나, 정밀도는 낮아지는 것이 일반적.

-> 때문에 정밀도 지표보다는 재현율 지표를 높이는 것이 머신러닝 모델의 주요한 목표인 경우 SMOTE를 적용하면 좋음

좋은 SMOTE 패키지일수록 재현율 증가율은 높이고 정밀도 감소율은 낮출 수 있도록 효과적으로 데이터를 증식함